use std::collections::{HashMap, HashSet};

use serde::{Deserialize, Serialize};

use crate::commands::connection::{AppState, DbPool};

use super::sql_util::{
    mysql_quote, mysql_string_literal, normalize_mysql_type, normalize_pg_type, normalize_sqlite_type,
    pg_quote,
};

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TableDdl {
    pub ddl: String,
    pub dialect: String,
    pub source: String,
}

struct PgColumnDdl {
    name: String,
    data_type: String,
    not_null: bool,
    default_expr: Option<String>,
    identity: String,
    serial_type: Option<String>,
}

struct PgConstraintDdl {
    name: String,
    definition: String,
}

fn ensure_semicolon(sql: String) -> String {
    let trimmed = sql.trim();
    if trimmed.ends_with(';') {
        trimmed.to_string()
    } else {
        format!("{trimmed};")
    }
}

fn render_pg_create_table(
    table: &str,
    columns: Vec<PgColumnDdl>,
    constraints: Vec<PgConstraintDdl>,
) -> String {
    let mut lines: Vec<String> = columns
        .into_iter()
        .map(|column| {
            let data_type = column.serial_type.as_deref().unwrap_or(&column.data_type);
            let mut line = format!("  {} {}", pg_quote(&column.name), data_type);

            match column.identity.as_str() {
                "a" => line.push_str(" GENERATED ALWAYS AS IDENTITY"),
                "d" => line.push_str(" GENERATED BY DEFAULT AS IDENTITY"),
                _ => {
                    if column.serial_type.is_none() {
                        if let Some(default_expr) = column.default_expr {
                            line.push_str(" DEFAULT ");
                            line.push_str(&default_expr);
                        }
                    }
                }
            }

            if column.not_null && column.serial_type.is_none() {
                line.push_str(" NOT NULL");
            }

            line
        })
        .collect();

    lines.extend(constraints.into_iter().map(|constraint| {
        format!(
            "  CONSTRAINT {} {}",
            pg_quote(&constraint.name),
            constraint.definition
        )
    }));

    format!(
        "CREATE TABLE {} (\n{}\n);",
        pg_quote(table),
        lines.join(",\n")
    )
}

async fn fetch_postgres_ddl(pool: sqlx::PgPool, table: &str) -> Result<TableDdl, String> {
    let relkind = sqlx::query_scalar::<_, String>(
        "SELECT c.relkind::text \
         FROM pg_catalog.pg_class c \
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace \
         WHERE c.relname = $1 AND n.nspname = 'public'",
    )
    .bind(table)
    .fetch_optional(&pool)
    .await
    .map_err(|e| e.to_string())?
    .ok_or_else(|| format!("Table not found: {table}"))?;

    if relkind != "r" && relkind != "p" {
        return Err("DDL is only available for tables".to_string());
    }

    let column_rows =
        sqlx::query_as::<_, (String, String, bool, Option<String>, String, Option<String>)>(
            "SELECT \
            a.attname, \
            pg_catalog.format_type(a.atttypid, a.atttypmod), \
            a.attnotnull, \
            pg_catalog.pg_get_expr(ad.adbin, ad.adrelid), \
            a.attidentity::text, \
            CASE \
                WHEN serial_seq.oid IS NULL THEN NULL \
                WHEN a.atttypid = 'pg_catalog.int2'::regtype THEN 'smallserial'::text \
                WHEN a.atttypid = 'pg_catalog.int4'::regtype THEN 'serial'::text \
                WHEN a.atttypid = 'pg_catalog.int8'::regtype THEN 'bigserial'::text \
                ELSE NULL \
            END \
         FROM pg_catalog.pg_attribute a \
         JOIN pg_catalog.pg_class c ON c.oid = a.attrelid \
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace \
         LEFT JOIN pg_catalog.pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum \
         LEFT JOIN LATERAL ( \
            SELECT seq.oid \
            FROM pg_catalog.pg_depend dep \
            JOIN pg_catalog.pg_class seq ON seq.oid = dep.objid AND seq.relkind = 'S' \
            WHERE dep.refobjid = a.attrelid \
                AND dep.refobjsubid = a.attnum \
                AND dep.deptype = 'a' \
                AND a.attidentity = '' \
                AND a.attnotnull \
                AND ad.adbin IS NOT NULL \
                AND pg_catalog.pg_get_expr(ad.adbin, ad.adrelid) LIKE 'nextval(%' \
            LIMIT 1 \
         ) serial_seq ON TRUE \
         WHERE c.relname = $1 \
            AND n.nspname = 'public' \
            AND a.attnum > 0 \
            AND NOT a.attisdropped \
         ORDER BY a.attnum",
        )
        .bind(table)
        .fetch_all(&pool)
        .await
        .map_err(|e| e.to_string())?;

    let columns = column_rows
        .into_iter()
        .map(
            |(name, data_type, not_null, default_expr, identity, serial_type)| PgColumnDdl {
                name,
                data_type,
                not_null,
                default_expr,
                identity,
                serial_type,
            },
        )
        .collect();

    let constraints = sqlx::query_as::<_, (String, String)>(
        "SELECT \
            con.conname, \
            pg_catalog.pg_get_constraintdef(con.oid, true) \
         FROM pg_catalog.pg_constraint con \
         JOIN pg_catalog.pg_class c ON c.oid = con.conrelid \
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace \
         WHERE c.relname = $1 \
            AND n.nspname = 'public' \
            AND con.contype IN ('p', 'u', 'c', 'f', 'x') \
         ORDER BY \
            CASE con.contype \
                WHEN 'p' THEN 1 \
                WHEN 'u' THEN 2 \
                WHEN 'f' THEN 3 \
                WHEN 'c' THEN 4 \
                WHEN 'x' THEN 5 \
                ELSE 6 \
            END, \
            con.conname",
    )
    .bind(table)
    .fetch_all(&pool)
    .await
    .map_err(|e| e.to_string())?
    .into_iter()
    .map(|(name, definition)| PgConstraintDdl { name, definition })
    .collect();

    Ok(TableDdl {
        ddl: render_pg_create_table(table, columns, constraints),
        dialect: "postgres".to_string(),
        source: "generated".to_string(),
    })
}

async fn fetch_mysql_ddl(pool: sqlx::MySqlPool, table: &str) -> Result<TableDdl, String> {
    let table_type = sqlx::query_scalar::<_, String>(
        "SELECT CAST(TABLE_TYPE AS CHAR) \
         FROM information_schema.TABLES \
         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?",
    )
    .bind(table)
    .fetch_optional(&pool)
    .await
    .map_err(|e| e.to_string())?
    .ok_or_else(|| format!("Table not found: {table}"))?;

    if table_type != "BASE TABLE" {
        return Err("DDL is only available for tables".to_string());
    }

    let sql = format!("SHOW CREATE TABLE {}", mysql_quote(table));
    let (_, ddl) = sqlx::query_as::<_, (String, String)>(sqlx::AssertSqlSafe(sql))
        .fetch_one(&pool)
        .await
        .map_err(|e| e.to_string())?;

    Ok(TableDdl {
        ddl: ensure_semicolon(ddl),
        dialect: "mysql".to_string(),
        source: "native".to_string(),
    })
}

async fn fetch_sqlite_ddl(pool: sqlx::SqlitePool, table: &str) -> Result<TableDdl, String> {
    let row = sqlx::query_as::<_, (String, Option<String>)>(
        "SELECT type, sql FROM sqlite_master \
         WHERE name = ? AND type IN ('table', 'view')",
    )
    .bind(table)
    .fetch_optional(&pool)
    .await
    .map_err(|e| e.to_string())?
    .ok_or_else(|| format!("Table not found: {table}"))?;

    if row.0 != "table" {
        return Err("DDL is only available for tables".to_string());
    }

    let ddl = row
        .1
        .ok_or_else(|| format!("No CREATE TABLE SQL is available for {table}"))?;

    Ok(TableDdl {
        ddl: ensure_semicolon(ddl),
        dialect: "sqlite".to_string(),
        source: "native".to_string(),
    })
}

#[tauri::command]
pub async fn fetch_table_ddl(
    connection_id: String,
    table: String,
    state: tauri::State<'_, AppState>,
) -> Result<TableDdl, String> {
    let pool = {
        let pools = state.pools.lock().unwrap();
        pools
            .get(&connection_id)
            .ok_or_else(|| "Connection not found".to_string())?
            .clone()
    };

    match pool {
        DbPool::Postgres(pg) => fetch_postgres_ddl(pg, &table).await,
        DbPool::MySql(mysql) => fetch_mysql_ddl(mysql, &table).await,
        DbPool::Sqlite(sqlite) => fetch_sqlite_ddl(sqlite, &table).await,
    }
}

// ── Table Structure (Columns tab) ────────────────────────────────────────────

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct StructureColumn {
    pub name: String,
    pub data_type: String,
    pub type_params: Option<String>,
    pub is_nullable: bool,
    pub is_primary: bool,
    pub is_foreign_key: bool,
    pub is_indexed: bool,
    pub default_value: Option<String>,
    /// Backend-only: attributes MySQL's MODIFY/CHANGE must restate.
    #[serde(skip)]
    pub mysql: Option<MySqlColumnMeta>,
}

/// Column attributes that MySQL's MODIFY/CHANGE COLUMN reset unless restated.
#[derive(Debug, Clone, Default)]
pub struct MySqlColumnMeta {
    /// Full COLUMN_TYPE, e.g. `int(10) unsigned zerofill` or `enum('a','b')`.
    pub column_type: String,
    pub extra: String,
    pub comment: String,
    pub charset: Option<String>,
    pub collation: Option<String>,
    pub generation_expr: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TableStructure {
    pub columns: Vec<StructureColumn>,
    pub dialect: String,
}

fn extract_type_params(full_type: &str) -> Option<String> {
    let open = full_type.find('(')?;
    let close = full_type.rfind(')')?;
    if close > open + 1 {
        Some(full_type[open + 1..close].trim().to_string())
    } else {
        None
    }
}

fn type_with_params(base_type: &str, params: Option<&str>) -> String {
    match params {
        Some(p) if !p.is_empty() => format!("{}({})", base_type, p),
        _ => base_type.to_string(),
    }
}

async fn fetch_pg_structure(
    pool: &sqlx::PgPool,
    table: &str,
) -> Result<TableStructure, String> {
    // Single query: column info + is_primary + is_foreign_key + is_indexed
    let rows = sqlx::query_as::<_, (String, String, String, String, bool, bool, bool, Option<String>)>(
        "SELECT \
            a.attname, \
            t.typname, \
            pg_catalog.format_type(a.atttypid, a.atttypmod), \
            CASE WHEN a.attnotnull THEN 'NO' ELSE 'YES' END, \
            EXISTS( \
                SELECT 1 FROM pg_catalog.pg_constraint con \
                WHERE con.conrelid = cl.oid \
                    AND con.contype = 'p' \
                    AND a.attnum = ANY(con.conkey) \
            ), \
            EXISTS( \
                SELECT 1 FROM pg_catalog.pg_constraint con \
                WHERE con.conrelid = cl.oid \
                    AND con.contype = 'f' \
                    AND a.attnum = ANY(con.conkey) \
            ), \
            EXISTS( \
                SELECT 1 FROM pg_catalog.pg_index ix \
                WHERE ix.indrelid = cl.oid \
                    AND NOT ix.indisprimary \
                    AND a.attnum = ANY(ix.indkey) \
            ), \
            pg_catalog.pg_get_expr(ad.adbin, ad.adrelid) \
        FROM pg_catalog.pg_attribute a \
        JOIN pg_catalog.pg_class cl ON cl.oid = a.attrelid \
        JOIN pg_catalog.pg_namespace n ON n.oid = cl.relnamespace \
        JOIN pg_catalog.pg_type t ON t.oid = a.atttypid \
        LEFT JOIN pg_catalog.pg_attrdef ad \
            ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum \
        WHERE cl.relname = $1 \
            AND n.nspname = 'public' \
            AND a.attnum > 0 \
            AND NOT a.attisdropped \
        ORDER BY a.attnum",
    )
    .bind(table)
    .fetch_all(pool)
    .await
    .map_err(|e| e.to_string())?;

    let columns = rows
        .into_iter()
        .map(
            |(name, typname, format_type, is_nullable, is_primary, is_fk, is_indexed, default_expr)| {
                StructureColumn {
                    name,
                    data_type: normalize_pg_type(&typname),
                    type_params: extract_type_params(&format_type),
                    is_nullable: is_nullable == "YES",
                    is_primary,
                    is_foreign_key: is_fk,
                    is_indexed,
                    default_value: default_expr,
                    mysql: None,
                }
            },
        )
        .collect();

    Ok(TableStructure {
        columns,
        dialect: "postgres".to_string(),
    })
}

#[derive(sqlx::FromRow)]
struct MySqlColumnRow {
    name: String,
    data_type: String,
    column_type: String,
    is_nullable: String,
    is_primary: i8,
    is_fk: i8,
    is_indexed: i8,
    default_value: Option<String>,
    extra: Option<String>,
    comment: Option<String>,
    charset: Option<String>,
    collation: Option<String>,
    generation_expr: Option<String>,
    is_mariadb: i8,
}

async fn fetch_mysql_structure(
    pool: &sqlx::MySqlPool,
    table: &str,
) -> Result<TableStructure, String> {
    let rows = sqlx::query_as::<_, MySqlColumnRow>(
        "SELECT \
            CAST(c.COLUMN_NAME AS CHAR) AS name, \
            CAST(CASE \
                WHEN c.COLUMN_TYPE LIKE '% unsigned%' THEN CONCAT(c.DATA_TYPE, ' unsigned') \
                ELSE c.DATA_TYPE \
            END AS CHAR) AS data_type, \
            CAST(c.COLUMN_TYPE AS CHAR) AS column_type, \
            CAST(c.IS_NULLABLE AS CHAR) AS is_nullable, \
            IF(c.COLUMN_KEY = 'PRI', 1, 0) AS is_primary, \
            IF(EXISTS( \
                SELECT 1 FROM information_schema.KEY_COLUMN_USAGE k \
                WHERE k.TABLE_SCHEMA = c.TABLE_SCHEMA \
                    AND k.TABLE_NAME = c.TABLE_NAME \
                    AND k.COLUMN_NAME = c.COLUMN_NAME \
                    AND k.REFERENCED_TABLE_NAME IS NOT NULL \
            ), 1, 0) AS is_fk, \
            IF(c.COLUMN_KEY IN ('MUL', 'UNI'), 1, 0) AS is_indexed, \
            CAST(c.COLUMN_DEFAULT AS CHAR) AS default_value, \
            CAST(c.EXTRA AS CHAR) AS extra, \
            CAST(c.COLUMN_COMMENT AS CHAR) AS comment, \
            CAST(c.CHARACTER_SET_NAME AS CHAR) AS charset, \
            CAST(c.COLLATION_NAME AS CHAR) AS collation, \
            CAST(c.GENERATION_EXPRESSION AS CHAR) AS generation_expr, \
            IF(VERSION() LIKE '%MariaDB%', 1, 0) AS is_mariadb \
        FROM information_schema.COLUMNS c \
        WHERE c.TABLE_SCHEMA = DATABASE() AND c.TABLE_NAME = ? \
        ORDER BY c.ORDINAL_POSITION",
    )
    .bind(table)
    .fetch_all(pool)
    .await
    .map_err(|e| e.to_string())?;

    let columns = rows
        .into_iter()
        .map(|row| {
            let data_type = normalize_mysql_type(&row.data_type);
            let extra = row.extra.unwrap_or_default();
            let default_value =
                mysql_default_sql(row.default_value, &extra, &data_type, row.is_mariadb != 0);
            StructureColumn {
                name: row.name,
                type_params: extract_type_params(&row.column_type),
                data_type,
                is_nullable: row.is_nullable == "YES",
                is_primary: row.is_primary != 0,
                is_foreign_key: row.is_fk != 0,
                is_indexed: row.is_indexed != 0,
                default_value,
                mysql: Some(MySqlColumnMeta {
                    column_type: row.column_type,
                    extra,
                    comment: row.comment.unwrap_or_default(),
                    charset: row.charset,
                    collation: row.collation,
                    generation_expr: row.generation_expr.filter(|e| !e.is_empty()),
                }),
            }
        })
        .collect();

    Ok(TableStructure {
        columns,
        dialect: "mysql".to_string(),
    })
}

/// MySQL's information_schema escapes quotes inside expressions
/// (`concat(_utf8mb4\'a\')`), which isn't valid SQL when pasted back.
fn unescape_mysql_expr(expr: &str) -> String {
    expr.replace("\\'", "'")
}

fn mysql_base_type(data_type: &str) -> &str {
    data_type.split(' ').next().unwrap_or(data_type)
}

fn is_mysql_string_type(data_type: &str) -> bool {
    matches!(
        mysql_base_type(data_type),
        "char" | "varchar" | "tinytext" | "text" | "mediumtext" | "longtext" | "enum" | "set"
    )
}

fn is_mysql_numeric_type(data_type: &str) -> bool {
    matches!(
        mysql_base_type(data_type),
        "tinyint" | "smallint" | "mediumint" | "int" | "integer" | "bigint" | "decimal"
            | "numeric" | "float" | "double" | "real" | "year" | "bit"
    )
}

/// Turns COLUMN_DEFAULT into SQL that can follow `DEFAULT`, matching what
/// Postgres' pg_get_expr returns. MySQL reports string literals unquoted and
/// expression defaults without their required parentheses; MariaDB already
/// returns SQL but reports "no default" as the string `NULL`.
fn mysql_default_sql(
    raw: Option<String>,
    extra: &str,
    data_type: &str,
    is_mariadb: bool,
) -> Option<String> {
    let raw = raw?;
    if is_mariadb {
        return (raw != "NULL").then_some(raw);
    }
    let lower = raw.to_ascii_lowercase();
    if lower.starts_with("current_timestamp") || lower.starts_with("now(") || lower.starts_with("localtime") {
        return Some(raw);
    }
    if extra.to_ascii_lowercase().contains("default_generated") {
        return Some(format!("({})", unescape_mysql_expr(&raw)));
    }
    if is_mysql_numeric_type(data_type) {
        Some(raw)
    } else {
        Some(mysql_string_literal(&raw))
    }
}

async fn fetch_sqlite_structure(
    pool: &sqlx::SqlitePool,
    table: &str,
) -> Result<TableStructure, String> {
    let rows = sqlx::query_as::<_, (i32, String, String, i32, Option<String>, i32)>(
        "SELECT * FROM pragma_table_info(?)",
    )
    .bind(table)
    .fetch_all(pool)
    .await
    .map_err(|e| e.to_string())?;

    // Collect FK column names
    let fk_rows = sqlx::query_as::<_, (String,)>(
        "SELECT \"from\" FROM pragma_foreign_key_list(?)",
    )
    .bind(table)
    .fetch_all(pool)
    .await
    .unwrap_or_default();
    let fk_cols: HashSet<String> = fk_rows.into_iter().map(|(c,)| c).collect();

    // Collect indexed column names (non-PK)
    let idx_rows = sqlx::query_as::<_, (String,)>(
        "SELECT ii.name FROM pragma_index_list(?) il, pragma_index_info(il.name) ii \
         WHERE il.origin != 'pk'",
    )
    .bind(table)
    .fetch_all(pool)
    .await
    .unwrap_or_default();
    let idx_cols: HashSet<String> = idx_rows.into_iter().map(|(c,)| c).collect();

    let columns = rows
        .into_iter()
        .map(|(_, name, declared_type, notnull, dflt_value, pk)| {
            let type_params = extract_type_params(&declared_type);
            let is_fk = fk_cols.contains(&name);
            let is_idx = idx_cols.contains(&name);
            StructureColumn {
                name,
                data_type: normalize_sqlite_type(&declared_type),
                type_params,
                is_nullable: notnull == 0,
                is_primary: pk > 0,
                is_foreign_key: is_fk,
                is_indexed: is_idx,
                default_value: dflt_value,
                mysql: None,
            }
        })
        .collect();

    Ok(TableStructure {
        columns,
        dialect: "sqlite".to_string(),
    })
}

#[tauri::command]
pub async fn fetch_table_structure(
    connection_id: String,
    table: String,
    state: tauri::State<'_, AppState>,
) -> Result<TableStructure, String> {
    let pool = {
        let pools = state.pools.lock().unwrap();
        pools
            .get(&connection_id)
            .ok_or_else(|| "Connection not found".to_string())?
            .clone()
    };

    match &pool {
        DbPool::Postgres(pg) => fetch_pg_structure(pg, &table).await,
        DbPool::MySql(mysql) => fetch_mysql_structure(mysql, &table).await,
        DbPool::Sqlite(sqlite) => fetch_sqlite_structure(sqlite, &table).await,
    }
}

// ── Structure changes (ALTER TABLE) ──────────────────────────────────────────

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ColumnEditPayload {
    pub original_name: String,
    pub name: String,
    pub data_type: String,
    pub type_params: Option<String>,
    pub nullable: bool,
    pub default_value: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ColumnAddPayload {
    pub name: String,
    pub data_type: String,
    pub type_params: Option<String>,
    pub nullable: bool,
    pub default_value: Option<String>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StructureChanges {
    pub edits: Vec<ColumnEditPayload>,
    pub drops: Vec<String>,
    pub adds: Vec<ColumnAddPayload>,
    pub reorder: Option<Vec<String>>,
}

fn col_map(current: &[StructureColumn]) -> HashMap<&str, &StructureColumn> {
    current.iter().map(|c| (c.name.as_str(), c)).collect()
}

/// Pairs each edit with its current column, skipping columns that are also
/// being dropped. An edit for a column that no longer exists means the UI is
/// out of date, so it's an error rather than a silent no-op.
fn resolve_edits<'a>(
    cols: &HashMap<&str, &'a StructureColumn>,
    changes: &'a StructureChanges,
) -> Result<Vec<(&'a StructureColumn, &'a ColumnEditPayload)>, String> {
    changes
        .edits
        .iter()
        .filter(|edit| !changes.drops.contains(&edit.original_name))
        .map(|edit| {
            cols.get(edit.original_name.as_str())
                .map(|&col| (col, edit))
                .ok_or_else(|| stale_column_error(&edit.original_name))
        })
        .collect()
}

fn stale_column_error(name: &str) -> String {
    format!("Column \"{name}\" no longer exists. Refresh the structure and try again.")
}

fn add_column_def(quoted_name: String, full_type: String, add: &ColumnAddPayload) -> String {
    let mut def = format!("{quoted_name} {full_type}");
    if !add.nullable {
        def.push_str(" NOT NULL");
    }
    if let Some(d) = add.default_value.as_deref().filter(|d| !d.is_empty()) {
        def.push_str(" DEFAULT ");
        def.push_str(d);
    }
    def
}

/// Drops run first so a rename can reuse a dropped column's name.
fn generate_pg_alter(
    table: &str,
    current: &[StructureColumn],
    changes: &StructureChanges,
) -> Result<Vec<String>, String> {
    if changes.reorder.is_some() {
        return Err(
            "Column reordering is not supported for PostgreSQL. Use the DDL tab to recreate the table."
                .to_string(),
        );
    }
    let mut stmts = Vec::new();
    let qt = pg_quote(table);
    let cols = col_map(current);
    let edits = resolve_edits(&cols, changes)?;

    for col_name in &changes.drops {
        stmts.push(format!(
            "ALTER TABLE {} DROP COLUMN {};",
            qt,
            pg_quote(col_name)
        ));
    }

    for (orig, edit) in edits {
        if edit.name != edit.original_name {
            stmts.push(format!(
                "ALTER TABLE {} RENAME COLUMN {} TO {};",
                qt,
                pg_quote(&edit.original_name),
                pg_quote(&edit.name)
            ));
        }

        let col_q = pg_quote(&edit.name);
        let new_type = type_with_params(&edit.data_type, edit.type_params.as_deref());
        let orig_type = type_with_params(&orig.data_type, orig.type_params.as_deref());

        if new_type != orig_type {
            stmts.push(format!(
                "ALTER TABLE {} ALTER COLUMN {} TYPE {};",
                qt, col_q, new_type
            ));
        }

        if edit.nullable != orig.is_nullable {
            stmts.push(format!(
                "ALTER TABLE {} ALTER COLUMN {} {} NOT NULL;",
                qt,
                col_q,
                if edit.nullable { "DROP" } else { "SET" }
            ));
        }

        if edit.default_value != orig.default_value {
            match &edit.default_value {
                Some(val) if !val.is_empty() => stmts.push(format!(
                    "ALTER TABLE {} ALTER COLUMN {} SET DEFAULT {};",
                    qt, col_q, val
                )),
                _ => stmts.push(format!(
                    "ALTER TABLE {} ALTER COLUMN {} DROP DEFAULT;",
                    qt, col_q
                )),
            }
        }
    }

    for add in &changes.adds {
        let full_type = type_with_params(&add.data_type, add.type_params.as_deref());
        stmts.push(format!(
            "ALTER TABLE {} ADD COLUMN {};",
            qt,
            add_column_def(pg_quote(&add.name), full_type, add)
        ));
    }

    Ok(stmts)
}

/// Renders a MySQL type with params, keeping modifiers after the params
/// (`int(10) unsigned`, not `int unsigned(10)`).
fn mysql_type_sql(data_type: &str, params: Option<&str>) -> String {
    match data_type.split_once(' ') {
        Some((base, modifiers)) => format!("{} {}", type_with_params(base, params), modifiers),
        None => type_with_params(data_type, params),
    }
}

fn mysql_definition_changed(orig: &StructureColumn, edit: &ColumnEditPayload) -> bool {
    edit.data_type != orig.data_type
        || edit.type_params != orig.type_params
        || edit.nullable != orig.is_nullable
        || edit.default_value != orig.default_value
}

/// Full column definition for MODIFY/CHANGE COLUMN. MySQL replaces the whole
/// definition, so anything not restated here — AUTO_INCREMENT, COMMENT,
/// charset, ON UPDATE, generated expressions — would be silently dropped.
fn mysql_column_def(orig: &StructureColumn, edit: Option<&ColumnEditPayload>) -> String {
    let (name, data_type, type_params, nullable, default_value) = match edit {
        Some(e) => (&e.name, &e.data_type, &e.type_params, e.nullable, &e.default_value),
        None => (&orig.name, &orig.data_type, &orig.type_params, orig.is_nullable, &orig.default_value),
    };
    let meta = orig.mysql.as_ref();
    let type_unchanged = *data_type == orig.data_type && *type_params == orig.type_params;
    let full_type = match meta {
        Some(m) if type_unchanged && !m.column_type.is_empty() => m.column_type.clone(),
        _ => mysql_type_sql(data_type, type_params.as_deref()),
    };
    let mut def = format!("{} {}", mysql_quote(name), full_type);

    let extra = meta.map(|m| m.extra.to_ascii_lowercase()).unwrap_or_default();
    let generated = meta.and_then(|m| m.generation_expr.as_deref());

    if let Some(m) = meta {
        if let (true, Some(cs), Some(coll)) = (is_mysql_string_type(data_type), &m.charset, &m.collation) {
            def.push_str(&format!(" CHARACTER SET {cs} COLLATE {coll}"));
        }
    }
    if let Some(expr) = generated {
        let kind = if extra.contains("stored") { "STORED" } else { "VIRTUAL" };
        def.push_str(&format!(" GENERATED ALWAYS AS ({}) {kind}", unescape_mysql_expr(expr)));
    }
    def.push_str(if nullable { " NULL" } else { " NOT NULL" });
    if generated.is_none() {
        if let Some(d) = default_value.as_deref().filter(|d| !d.is_empty()) {
            def.push_str(" DEFAULT ");
            def.push_str(d);
        }
    }
    if let Some(m) = meta {
        if extra.contains("auto_increment") {
            def.push_str(" AUTO_INCREMENT");
        }
        if let Some(idx) = extra.find("on update ") {
            def.push_str(" ON UPDATE ");
            def.push_str(m.extra[idx + "on update ".len()..].trim());
        }
        if extra.contains("invisible") {
            def.push_str(" INVISIBLE");
        }
        if !m.comment.is_empty() {
            def.push_str(" COMMENT ");
            def.push_str(&mysql_string_literal(&m.comment));
        }
    }
    def
}

/// Emits one ALTER TABLE: MySQL auto-commits every DDL statement, so a single
/// statement is the only way to make a save all-or-nothing. Clauses apply in
/// order and later clauses see earlier renames, so drops go first and column
/// moves are emitted in the target order with AFTER using the new names.
fn generate_mysql_alter(
    table: &str,
    current: &[StructureColumn],
    changes: &StructureChanges,
) -> Result<Vec<String>, String> {
    let cols = col_map(current);
    let edits: HashMap<&str, &ColumnEditPayload> = resolve_edits(&cols, changes)?
        .into_iter()
        .map(|(col, edit)| (col.name.as_str(), edit))
        .collect();
    let new_name = |orig: &str| edits.get(orig).map_or(orig.to_string(), |e| e.name.clone());

    let mut clauses: Vec<String> = changes
        .drops
        .iter()
        .map(|name| format!("DROP COLUMN {}", mysql_quote(name)))
        .collect();

    let surviving: Vec<&str> = current
        .iter()
        .map(|c| c.name.as_str())
        .filter(|name| !changes.drops.iter().any(|d| d == name))
        .collect();
    let target: Vec<&str> = match &changes.reorder {
        Some(order) => {
            let order: Vec<&str> = order
                .iter()
                .map(String::as_str)
                .filter(|name| !changes.drops.iter().any(|d| d == name))
                .collect();
            let mut sorted_order = order.clone();
            let mut sorted_surviving = surviving.clone();
            sorted_order.sort_unstable();
            sorted_surviving.sort_unstable();
            if sorted_order != sorted_surviving {
                return Err("The column order is out of date. Refresh the structure and try again.".to_string());
            }
            order
        }
        None => surviving.clone(),
    };

    // Replay moves on a simulated column list so only columns that actually
    // move get a FIRST/AFTER clause.
    let mut simulated = surviving;
    for (i, &orig_name) in target.iter().enumerate() {
        let col = cols[orig_name];
        let edit = edits.get(orig_name).copied();

        let position = if simulated[i] != orig_name {
            let from = simulated.iter().position(|n| *n == orig_name).unwrap_or(i);
            let moved = simulated.remove(from);
            simulated.insert(i, moved);
            if i == 0 {
                " FIRST".to_string()
            } else {
                format!(" AFTER {}", mysql_quote(&new_name(target[i - 1])))
            }
        } else {
            String::new()
        };

        let renamed = edit.is_some_and(|e| e.name != e.original_name);
        let definition_changed = edit.is_some_and(|e| mysql_definition_changed(col, e));

        if definition_changed || !position.is_empty() {
            let def = mysql_column_def(col, edit);
            if renamed {
                clauses.push(format!("CHANGE COLUMN {} {def}{position}", mysql_quote(orig_name)));
            } else {
                clauses.push(format!("MODIFY COLUMN {def}{position}"));
            }
        } else if renamed {
            // Rename only: leave the definition untouched.
            clauses.push(format!(
                "RENAME COLUMN {} TO {}",
                mysql_quote(orig_name),
                mysql_quote(&new_name(orig_name))
            ));
        }
    }

    for add in &changes.adds {
        let full_type = mysql_type_sql(&add.data_type, add.type_params.as_deref());
        clauses.push(format!("ADD COLUMN {}", add_column_def(mysql_quote(&add.name), full_type, add)));
    }

    if clauses.is_empty() {
        return Ok(vec![]);
    }
    Ok(vec![format!("ALTER TABLE {} {};", mysql_quote(table), clauses.join(", "))])
}

/// Drops run first so a rename can reuse a dropped column's name.
fn generate_sqlite_alter(
    table: &str,
    current: &[StructureColumn],
    changes: &StructureChanges,
) -> Result<Vec<String>, String> {
    if changes.reorder.is_some() {
        return Err(
            "Column reordering is not supported for SQLite. Use the DDL tab to recreate the table."
                .to_string(),
        );
    }
    let mut stmts = Vec::new();
    let qt = pg_quote(table);
    let cols = col_map(current);
    let edits = resolve_edits(&cols, changes)?;

    for (orig, edit) in &edits {
        let new_type = type_with_params(&edit.data_type, edit.type_params.as_deref());
        let orig_type = type_with_params(&orig.data_type, orig.type_params.as_deref());

        if new_type != orig_type {
            return Err(
                "SQLite does not support changing column types. Use the DDL tab to recreate the table."
                    .to_string(),
            );
        }
        if edit.nullable != orig.is_nullable {
            return Err(
                "SQLite does not support changing column nullability. Use the DDL tab to recreate the table."
                    .to_string(),
            );
        }
        if edit.default_value != orig.default_value {
            return Err(
                "SQLite does not support changing column defaults. Use the DDL tab to recreate the table."
                    .to_string(),
            );
        }
    }

    for col_name in &changes.drops {
        stmts.push(format!(
            "ALTER TABLE {} DROP COLUMN {};",
            qt,
            pg_quote(col_name)
        ));
    }

    for (_, edit) in &edits {
        if edit.name != edit.original_name {
            stmts.push(format!(
                "ALTER TABLE {} RENAME COLUMN {} TO {};",
                qt,
                pg_quote(&edit.original_name),
                pg_quote(&edit.name)
            ));
        }
    }

    for add in &changes.adds {
        let full_type = type_with_params(&add.data_type, add.type_params.as_deref());
        stmts.push(format!(
            "ALTER TABLE {} ADD COLUMN {};",
            qt,
            add_column_def(pg_quote(&add.name), full_type, add)
        ));
    }

    Ok(stmts)
}

#[tauri::command]
pub async fn apply_structure_changes(
    connection_id: String,
    table: String,
    changes: StructureChanges,
    state: tauri::State<'_, AppState>,
) -> Result<Vec<String>, String> {
    let pool = {
        let pools = state.pools.lock().unwrap();
        pools
            .get(&connection_id)
            .ok_or_else(|| "Connection not found".to_string())?
            .clone()
    };

    // Fetch current structure to compute diffs
    let current = match &pool {
        DbPool::Postgres(pg) => fetch_pg_structure(pg, &table).await?,
        DbPool::MySql(mysql) => fetch_mysql_structure(mysql, &table).await?,
        DbPool::Sqlite(sqlite) => fetch_sqlite_structure(sqlite, &table).await?,
    };

    let stmts = match &pool {
        DbPool::Postgres(_) => generate_pg_alter(&table, &current.columns, &changes),
        DbPool::MySql(_) => generate_mysql_alter(&table, &current.columns, &changes),
        DbPool::Sqlite(_) => generate_sqlite_alter(&table, &current.columns, &changes),
    }?;

    if stmts.is_empty() {
        return Ok(stmts);
    }

    pool.execute_in_transaction(&stmts)
        .await
        .map_err(|e| e.to_string())?;

    Ok(stmts)
}

#[cfg(test)]
mod tests {
    use super::*;
    use sqlx::mysql::{MySqlConnectOptions, MySqlPoolOptions};
    use sqlx::postgres::PgPoolOptions;
    use testcontainers_modules::{mysql::Mysql, postgres::Postgres, testcontainers::runners::AsyncRunner};

    #[test]
    fn ensure_semicolon_appends_only_when_missing() {
        assert_eq!(
            ensure_semicolon("CREATE TABLE items (id integer)".to_string()),
            "CREATE TABLE items (id integer);"
        );
        assert_eq!(
            ensure_semicolon("CREATE TABLE items (id integer);".to_string()),
            "CREATE TABLE items (id integer);"
        );
    }

    #[test]
    fn render_pg_create_table_includes_columns_and_constraints() {
        let ddl = render_pg_create_table(
            "items",
            vec![
                PgColumnDdl {
                    name: "id".to_string(),
                    data_type: "integer".to_string(),
                    not_null: true,
                    default_expr: Some("nextval('items_id_seq'::regclass)".to_string()),
                    identity: String::new(),
                    serial_type: None,
                },
                PgColumnDdl {
                    name: "name".to_string(),
                    data_type: "text".to_string(),
                    not_null: true,
                    default_expr: Some("'untitled'::text".to_string()),
                    identity: String::new(),
                    serial_type: None,
                },
            ],
            vec![
                PgConstraintDdl {
                    name: "items_pkey".to_string(),
                    definition: "PRIMARY KEY (id)".to_string(),
                },
                PgConstraintDdl {
                    name: "items_name_key".to_string(),
                    definition: "UNIQUE (name)".to_string(),
                },
                PgConstraintDdl {
                    name: "items_name_check".to_string(),
                    definition: "CHECK (name <> ''::text)".to_string(),
                },
            ],
        );

        assert!(ddl.contains("CREATE TABLE \"items\""));
        assert!(ddl.contains("\"id\" integer DEFAULT nextval('items_id_seq'::regclass) NOT NULL"));
        assert!(ddl.contains("\"name\" text DEFAULT 'untitled'::text NOT NULL"));
        assert!(ddl.contains("CONSTRAINT \"items_pkey\" PRIMARY KEY (id)"));
        assert!(ddl.contains("CONSTRAINT \"items_name_key\" UNIQUE (name)"));
        assert!(ddl.contains("CONSTRAINT \"items_name_check\" CHECK (name <> ''::text)"));
    }

    #[test]
    fn render_pg_create_table_prefers_identity_over_default() {
        let ddl = render_pg_create_table(
            "items",
            vec![PgColumnDdl {
                name: "id".to_string(),
                data_type: "bigint".to_string(),
                not_null: true,
                default_expr: Some("nextval('items_id_seq'::regclass)".to_string()),
                identity: "d".to_string(),
                serial_type: None,
            }],
            vec![],
        );

        assert!(ddl.contains("\"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assert!(!ddl.contains("nextval"));
    }

    #[test]
    fn render_pg_create_table_uses_serial_for_owned_sequence_defaults() {
        let ddl = render_pg_create_table(
            "items",
            vec![PgColumnDdl {
                name: "id".to_string(),
                data_type: "integer".to_string(),
                not_null: true,
                default_expr: Some("nextval('items_id_seq'::regclass)".to_string()),
                identity: String::new(),
                serial_type: Some("serial".to_string()),
            }],
            vec![PgConstraintDdl {
                name: "items_pkey".to_string(),
                definition: "PRIMARY KEY (id)".to_string(),
            }],
        );

        assert!(ddl.contains("\"id\" serial"));
        assert!(!ddl.contains("nextval"));
        assert!(ddl.contains("CONSTRAINT \"items_pkey\" PRIMARY KEY (id)"));
    }

    #[tokio::test]
    #[ignore = "requires Docker"]
    async fn fetch_postgres_ddl_preserves_serial_and_table_constraints() {
        let container = Postgres::default().start().await.unwrap();
        let port = container.get_host_port_ipv4(5432).await.unwrap();
        let url = format!("postgres://postgres:postgres@127.0.0.1:{port}/postgres");
        let pool = PgPoolOptions::new()
            .max_connections(1)
            .connect(&url)
            .await
            .unwrap();

        sqlx::query("CREATE TABLE parents (id SERIAL PRIMARY KEY)")
            .execute(&pool)
            .await
            .unwrap();
        sqlx::query(
            "CREATE TABLE items ( \
                id SERIAL PRIMARY KEY, \
                name TEXT NOT NULL UNIQUE, \
                quantity INTEGER NOT NULL CHECK (quantity > 0), \
                parent_id INTEGER REFERENCES parents(id) \
             )",
        )
        .execute(&pool)
        .await
        .unwrap();

        let ddl = fetch_postgres_ddl(pool, "items").await.unwrap().ddl;

        assert!(ddl.contains("\"id\" serial"));
        assert!(!ddl.contains("nextval"));
        assert!(ddl.contains("PRIMARY KEY (id)"));
        assert!(ddl.contains("UNIQUE (name)"));
        assert!(ddl.contains("CHECK"));
        assert!(ddl.contains("quantity > 0"));
        assert!(ddl.contains("FOREIGN KEY (parent_id) REFERENCES parents(id)"));
    }

    // ── Table Structure tests ────────────────────────────────────────────

    // -- Helpers --

    fn test_col(name: &str, data_type: &str, nullable: bool, default: Option<&str>) -> StructureColumn {
        StructureColumn {
            name: name.to_string(),
            data_type: data_type.to_string(),
            type_params: None,
            is_nullable: nullable,
            is_primary: name == "id",
            is_foreign_key: false,
            is_indexed: false,
            default_value: default.map(|s| s.to_string()),
            mysql: None,
        }
    }

    fn test_col_with_params(name: &str, data_type: &str, params: &str, nullable: bool, default: Option<&str>) -> StructureColumn {
        StructureColumn {
            type_params: Some(params.to_string()),
            ..test_col(name, data_type, nullable, default)
        }
    }

    fn empty_changes() -> StructureChanges {
        StructureChanges { edits: vec![], drops: vec![], adds: vec![], reorder: None }
    }

    fn edit(original: &str, name: &str, dt: &str, params: Option<&str>, nullable: bool, default: Option<&str>) -> ColumnEditPayload {
        ColumnEditPayload {
            original_name: original.into(),
            name: name.into(),
            data_type: dt.into(),
            type_params: params.map(|s| s.into()),
            nullable,
            default_value: default.map(|s| s.into()),
        }
    }

    fn add(name: &str, dt: &str, params: Option<&str>, nullable: bool, default: Option<&str>) -> ColumnAddPayload {
        ColumnAddPayload {
            name: name.into(),
            data_type: dt.into(),
            type_params: params.map(|s| s.into()),
            nullable,
            default_value: default.map(|s| s.into()),
        }
    }

    // -- extract_type_params --

    #[test]
    fn extract_type_params_basic() {
        assert_eq!(extract_type_params("varchar(255)"), Some("255".into()));
        assert_eq!(extract_type_params("numeric(10,2)"), Some("10,2".into()));
        assert_eq!(extract_type_params("integer"), None);
        assert_eq!(extract_type_params("text"), None);
    }

    #[test]
    fn extract_type_params_edge_cases() {
        assert_eq!(extract_type_params("char()"), None); // empty parens
        assert_eq!(extract_type_params("int(11) unsigned"), Some("11".into())); // trailing suffix after paren
        assert_eq!(extract_type_params("character varying(255)"), Some("255".into())); // PG format_type output
        assert_eq!(extract_type_params("numeric( 10 , 2 )"), Some("10 , 2".into())); // whitespace preserved
        assert_eq!(extract_type_params(""), None);
        assert_eq!(extract_type_params("double precision"), None); // space but no parens
    }

    // -- type_with_params --

    #[test]
    fn type_with_params_roundtrip() {
        assert_eq!(type_with_params("varchar", Some("255")), "varchar(255)");
        assert_eq!(type_with_params("integer", None), "integer");
        assert_eq!(type_with_params("numeric", Some("10,2")), "numeric(10,2)");
        assert_eq!(type_with_params("text", Some("")), "text"); // empty string treated as no params
        assert_eq!(type_with_params("double precision", None), "double precision");
    }

    // ── PostgreSQL ALTER ─────────────────────────────────────────────────

    #[test]
    fn pg_empty_changes_produces_nothing() {
        let stmts = generate_pg_alter("t", &[test_col("a", "text", true, None)], &empty_changes()).unwrap();
        assert!(stmts.is_empty());
    }

    #[test]
    fn pg_no_op_edit_produces_nothing() {
        let current = vec![test_col("name", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("name", "name", "text", None, true, None)],
            ..empty_changes()
        };
        assert!(generate_pg_alter("t", &current, &changes).unwrap().is_empty());
    }

    #[test]
    fn pg_edit_nonexistent_column_errors() {
        let current = vec![test_col("a", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("does_not_exist", "b", "text", None, true, None)],
            ..empty_changes()
        };
        let err = generate_pg_alter("t", &current, &changes).unwrap_err();
        assert!(err.contains("no longer exists"));
    }

    #[test]
    fn pg_drops_run_before_renames_so_names_can_be_reused() {
        let current = vec![test_col("name", "text", true, None), test_col("full_name", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("full_name", "name", "text", None, true, None)],
            drops: vec!["name".into()],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(
            stmts,
            vec![
                "ALTER TABLE \"t\" DROP COLUMN \"name\";",
                "ALTER TABLE \"t\" RENAME COLUMN \"full_name\" TO \"name\";",
            ]
        );
    }

    #[test]
    fn pg_edits_on_dropped_columns_are_ignored() {
        let current = vec![test_col("a", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("a", "b", "integer", None, false, None)],
            drops: vec!["a".into()],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" DROP COLUMN \"a\";"]);
    }

    #[test]
    fn pg_rename() {
        let current = vec![test_col("old", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("old", "new", "text", None, true, None)],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" RENAME COLUMN \"old\" TO \"new\";"]);
    }

    #[test]
    fn pg_type_change() {
        let current = vec![test_col("age", "integer", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("age", "age", "bigint", None, true, None)],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ALTER COLUMN \"age\" TYPE bigint;"]);
    }

    #[test]
    fn pg_type_change_with_params() {
        let current = vec![test_col_with_params("name", "varchar", "50", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("name", "name", "varchar", Some("255"), true, None)],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ALTER COLUMN \"name\" TYPE varchar(255);"]);
    }

    #[test]
    fn pg_set_not_null() {
        let current = vec![test_col("name", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("name", "name", "text", None, false, None)],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ALTER COLUMN \"name\" SET NOT NULL;"]);
    }

    #[test]
    fn pg_drop_not_null() {
        let current = vec![test_col("name", "text", false, None)];
        let changes = StructureChanges {
            edits: vec![edit("name", "name", "text", None, true, None)],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ALTER COLUMN \"name\" DROP NOT NULL;"]);
    }

    #[test]
    fn pg_set_default() {
        let current = vec![test_col("name", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("name", "name", "text", None, true, Some("'hello'"))],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ALTER COLUMN \"name\" SET DEFAULT 'hello';"]);
    }

    #[test]
    fn pg_drop_default() {
        let current = vec![test_col("name", "text", true, Some("'old'"))];
        let changes = StructureChanges {
            edits: vec![edit("name", "name", "text", None, true, None)],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ALTER COLUMN \"name\" DROP DEFAULT;"]);
    }

    #[test]
    fn pg_rename_plus_type_plus_nullable_plus_default_all_at_once() {
        let current = vec![test_col("old", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("old", "new", "varchar", Some("100"), false, Some("'x'"))],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts.len(), 4);
        assert_eq!(stmts[0], "ALTER TABLE \"t\" RENAME COLUMN \"old\" TO \"new\";");
        assert_eq!(stmts[1], "ALTER TABLE \"t\" ALTER COLUMN \"new\" TYPE varchar(100);");
        assert_eq!(stmts[2], "ALTER TABLE \"t\" ALTER COLUMN \"new\" SET NOT NULL;");
        assert_eq!(stmts[3], "ALTER TABLE \"t\" ALTER COLUMN \"new\" SET DEFAULT 'x';");
    }

    #[test]
    fn pg_multiple_edits_on_different_columns() {
        let current = vec![test_col("a", "text", true, None), test_col("b", "integer", true, None)];
        let changes = StructureChanges {
            edits: vec![
                edit("a", "a_renamed", "text", None, true, None),
                edit("b", "b", "bigint", None, true, None),
            ],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts.len(), 2);
        assert!(stmts[0].contains("RENAME COLUMN \"a\" TO \"a_renamed\""));
        assert!(stmts[1].contains("ALTER COLUMN \"b\" TYPE bigint"));
    }

    #[test]
    fn pg_drop_column() {
        let changes = StructureChanges { drops: vec!["old".into()], ..empty_changes() };
        let stmts = generate_pg_alter("t", &[], &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" DROP COLUMN \"old\";"]);
    }

    #[test]
    fn pg_drop_multiple_columns() {
        let changes = StructureChanges { drops: vec!["a".into(), "b".into()], ..empty_changes() };
        let stmts = generate_pg_alter("t", &[], &changes).unwrap();
        assert_eq!(stmts.len(), 2);
    }

    #[test]
    fn pg_add_column_nullable_no_default() {
        let changes = StructureChanges { adds: vec![add("col", "text", None, true, None)], ..empty_changes() };
        let stmts = generate_pg_alter("t", &[], &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ADD COLUMN \"col\" text;"]);
    }

    #[test]
    fn pg_add_column_not_null_with_default() {
        let changes = StructureChanges { adds: vec![add("col", "integer", None, false, Some("0"))], ..empty_changes() };
        let stmts = generate_pg_alter("t", &[], &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ADD COLUMN \"col\" integer NOT NULL DEFAULT 0;"]);
    }

    #[test]
    fn pg_add_column_with_type_params() {
        let changes = StructureChanges { adds: vec![add("price", "numeric", Some("10,2"), false, Some("0"))], ..empty_changes() };
        let stmts = generate_pg_alter("t", &[], &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ADD COLUMN \"price\" numeric(10,2) NOT NULL DEFAULT 0;"]);
    }

    #[test]
    fn pg_special_chars_in_names_are_quoted() {
        let current = vec![test_col("my column", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("my column", "new col", "text", None, true, None)],
            ..empty_changes()
        };
        let stmts = generate_pg_alter("my table", &current, &changes).unwrap();
        assert_eq!(stmts[0], "ALTER TABLE \"my table\" RENAME COLUMN \"my column\" TO \"new col\";");
    }

    #[test]
    fn pg_quotes_in_name_are_escaped() {
        let changes = StructureChanges { drops: vec!["col\"name".into()], ..empty_changes() };
        let stmts = generate_pg_alter("t", &[], &changes).unwrap();
        assert_eq!(stmts[0], "ALTER TABLE \"t\" DROP COLUMN \"col\"\"name\";");
    }

    #[test]
    fn pg_rejects_reorder() {
        let changes = StructureChanges { reorder: Some(vec!["a".into()]), ..empty_changes() };
        let err = generate_pg_alter("t", &[], &changes).unwrap_err();
        assert!(err.contains("not supported"));
    }

    #[test]
    fn pg_combined_edits_drops_and_adds() {
        let current = vec![
            test_col("keep", "text", true, None),
            test_col("drop_me", "integer", true, None),
        ];
        let changes = StructureChanges {
            edits: vec![edit("keep", "keep", "varchar", Some("255"), true, None)],
            drops: vec!["drop_me".into()],
            adds: vec![add("new", "boolean", None, false, Some("false"))],
            reorder: None,
        };
        let stmts = generate_pg_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts.len(), 3);
        assert!(stmts[0].contains("DROP COLUMN \"drop_me\""));
        assert!(stmts[1].contains("TYPE varchar(255)"));
        assert!(stmts[2].contains("ADD COLUMN \"new\" boolean NOT NULL DEFAULT false"));
    }

    // ── MySQL ALTER ──────────────────────────────────────────────────────

    fn mysql_alter(current: &[StructureColumn], changes: &StructureChanges) -> Vec<String> {
        generate_mysql_alter("t", current, changes).unwrap()
    }

    fn mysql_col(name: &str, data_type: &str, nullable: bool, default: Option<&str>, meta: MySqlColumnMeta) -> StructureColumn {
        StructureColumn { mysql: Some(meta), ..test_col(name, data_type, nullable, default) }
    }

    #[test]
    fn mysql_empty_changes_produces_nothing() {
        assert!(mysql_alter(&[test_col("a", "text", true, None)], &empty_changes()).is_empty());
    }

    #[test]
    fn mysql_no_op_edit_produces_nothing() {
        let current = vec![test_col("name", "varchar", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("name", "name", "varchar", None, true, None)],
            ..empty_changes()
        };
        assert!(mysql_alter(&current, &changes).is_empty());
    }

    #[test]
    fn mysql_edit_nonexistent_column_errors() {
        let changes = StructureChanges {
            edits: vec![edit("ghost", "ghost", "int", None, true, None)],
            ..empty_changes()
        };
        let err = generate_mysql_alter("t", &[test_col("a", "int", true, None)], &changes).unwrap_err();
        assert!(err.contains("no longer exists"));
    }

    #[test]
    fn mysql_rename_only_uses_rename_not_modify() {
        let current = vec![test_col("old", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("old", "new", "text", None, true, None)],
            ..empty_changes()
        };
        assert_eq!(mysql_alter(&current, &changes), vec!["ALTER TABLE `t` RENAME COLUMN `old` TO `new`;"]);
    }

    #[test]
    fn mysql_type_change_uses_modify() {
        let current = vec![test_col("age", "int", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("age", "age", "bigint", None, true, None)],
            ..empty_changes()
        };
        assert_eq!(mysql_alter(&current, &changes), vec!["ALTER TABLE `t` MODIFY COLUMN `age` bigint NULL;"]);
    }

    #[test]
    fn mysql_modify_includes_full_definition() {
        let current = vec![test_col("name", "varchar", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("name", "name", "varchar", Some("100"), false, Some("'test'"))],
            ..empty_changes()
        };
        assert_eq!(
            mysql_alter(&current, &changes),
            vec!["ALTER TABLE `t` MODIFY COLUMN `name` varchar(100) NOT NULL DEFAULT 'test';"]
        );
    }

    #[test]
    fn mysql_rename_and_modify_uses_one_change_clause() {
        let current = vec![test_col("old", "int", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("old", "new", "bigint", None, false, Some("0"))],
            ..empty_changes()
        };
        assert_eq!(
            mysql_alter(&current, &changes),
            vec!["ALTER TABLE `t` CHANGE COLUMN `old` `new` bigint NOT NULL DEFAULT 0;"]
        );
    }

    #[test]
    fn mysql_nullable_only_change_triggers_modify() {
        let current = vec![test_col("col", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("col", "col", "text", None, false, None)],
            ..empty_changes()
        };
        assert_eq!(mysql_alter(&current, &changes), vec!["ALTER TABLE `t` MODIFY COLUMN `col` text NOT NULL;"]);
    }

    #[test]
    fn mysql_everything_is_one_statement() {
        let changes = StructureChanges {
            drops: vec!["old".into()],
            adds: vec![add("new", "varchar", Some("255"), true, None)],
            ..empty_changes()
        };
        assert_eq!(
            mysql_alter(&[test_col("old", "int", true, None)], &changes),
            vec!["ALTER TABLE `t` DROP COLUMN `old`, ADD COLUMN `new` varchar(255);"]
        );
    }

    #[test]
    fn mysql_add_not_null_with_default() {
        let changes = StructureChanges {
            adds: vec![add("active", "boolean", None, false, Some("true"))],
            ..empty_changes()
        };
        assert_eq!(
            mysql_alter(&[], &changes),
            vec!["ALTER TABLE `t` ADD COLUMN `active` boolean NOT NULL DEFAULT true;"]
        );
    }

    #[test]
    fn mysql_backtick_in_name_is_escaped() {
        let changes = StructureChanges { drops: vec!["col`name".into()], ..empty_changes() };
        assert_eq!(mysql_alter(&[], &changes), vec!["ALTER TABLE `t` DROP COLUMN `col``name`;"]);
    }

    #[test]
    fn mysql_drop_runs_before_rename_to_the_dropped_name() {
        let current = vec![test_col("name", "text", true, None), test_col("full_name", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("full_name", "name", "text", None, true, None)],
            drops: vec!["name".into()],
            ..empty_changes()
        };
        assert_eq!(
            mysql_alter(&current, &changes),
            vec!["ALTER TABLE `t` DROP COLUMN `name`, RENAME COLUMN `full_name` TO `name`;"]
        );
    }

    #[test]
    fn mysql_reorder_only_moves_columns_that_change_position() {
        let current = vec![
            test_col("a", "text", true, None),
            test_col("b", "int", true, None),
            test_col("c", "text", true, None),
        ];
        let changes = StructureChanges {
            reorder: Some(vec!["c".into(), "a".into(), "b".into()]),
            ..empty_changes()
        };
        assert_eq!(mysql_alter(&current, &changes), vec!["ALTER TABLE `t` MODIFY COLUMN `c` text NULL FIRST;"]);
    }

    #[test]
    fn mysql_reorder_uses_edited_column_definition() {
        let current = vec![test_col("a", "text", true, None), test_col("b", "int", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("a", "a", "varchar", Some("100"), false, Some("'x'"))],
            reorder: Some(vec!["b".into(), "a".into()]),
            ..empty_changes()
        };
        assert_eq!(
            mysql_alter(&current, &changes),
            vec!["ALTER TABLE `t` MODIFY COLUMN `b` int NULL FIRST, MODIFY COLUMN `a` varchar(100) NOT NULL DEFAULT 'x';"]
        );
    }

    #[test]
    fn mysql_reorder_after_renamed_column_uses_new_name() {
        let current = vec![
            test_col("a", "int", true, None),
            test_col("b", "int", true, None),
            test_col("c", "int", true, None),
        ];
        let changes = StructureChanges {
            edits: vec![edit("a", "a2", "int", None, true, None)],
            reorder: Some(vec!["a".into(), "c".into(), "b".into()]),
            ..empty_changes()
        };
        assert_eq!(
            mysql_alter(&current, &changes),
            vec!["ALTER TABLE `t` RENAME COLUMN `a` TO `a2`, MODIFY COLUMN `c` int NULL AFTER `a2`;"]
        );
    }

    #[test]
    fn mysql_reorder_ignores_dropped_columns() {
        let current = vec![
            test_col("a", "int", true, None),
            test_col("b", "int", true, None),
            test_col("c", "int", true, None),
        ];
        let changes = StructureChanges {
            drops: vec!["b".into()],
            reorder: Some(vec!["c".into(), "b".into(), "a".into()]),
            ..empty_changes()
        };
        assert_eq!(
            mysql_alter(&current, &changes),
            vec!["ALTER TABLE `t` DROP COLUMN `b`, MODIFY COLUMN `c` int NULL FIRST;"]
        );
    }

    #[test]
    fn mysql_reorder_with_unknown_columns_errors() {
        let current = vec![test_col("a", "text", true, None)];
        let changes = StructureChanges {
            reorder: Some(vec!["nonexistent".into(), "a".into()]),
            ..empty_changes()
        };
        assert!(generate_mysql_alter("t", &current, &changes).unwrap_err().contains("out of date"));
    }

    #[test]
    fn mysql_modify_preserves_auto_increment() {
        let meta = MySqlColumnMeta {
            column_type: "int unsigned".into(),
            extra: "auto_increment".into(),
            ..Default::default()
        };
        let current = vec![
            mysql_col("id", "int unsigned", false, None, meta),
            test_col("b", "int", true, None),
        ];
        let changes = StructureChanges {
            reorder: Some(vec!["b".into(), "id".into()]),
            ..empty_changes()
        };
        assert_eq!(
            mysql_alter(&current, &changes),
            vec!["ALTER TABLE `t` MODIFY COLUMN `b` int NULL FIRST;"]
        );
        let changes = StructureChanges {
            reorder: Some(vec!["id".into(), "b".into()]),
            edits: vec![edit("id", "id", "bigint unsigned", None, false, None)],
            ..empty_changes()
        };
        assert_eq!(
            mysql_alter(&current, &changes),
            vec!["ALTER TABLE `t` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT;"]
        );
    }

    // -- mysql_column_def --

    #[test]
    fn mysql_column_def_full() {
        let col = StructureColumn {
            type_params: Some("10,2".into()),
            ..test_col("price", "decimal", false, Some("0.00"))
        };
        assert_eq!(mysql_column_def(&col, None), "`price` decimal(10,2) NOT NULL DEFAULT 0.00");
    }

    #[test]
    fn mysql_column_def_nullable_no_default() {
        let col = test_col("notes", "text", true, None);
        assert_eq!(mysql_column_def(&col, None), "`notes` text NULL");
    }

    #[test]
    fn mysql_column_def_empty_default_is_omitted() {
        let col = test_col("col", "int", true, Some(""));
        assert_eq!(mysql_column_def(&col, None), "`col` int NULL");
    }

    #[test]
    fn mysql_column_def_restates_attributes_modify_would_drop() {
        let col = mysql_col(
            "status",
            "varchar",
            false,
            Some("'active'"),
            MySqlColumnMeta {
                column_type: "varchar(20)".into(),
                comment: "it's \\ here".into(),
                charset: Some("latin1".into()),
                collation: Some("latin1_swedish_ci".into()),
                ..Default::default()
            },
        );
        assert_eq!(
            mysql_column_def(&col, None),
            "`status` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL DEFAULT 'active' COMMENT 'it''s \\\\ here'"
        );

        let updated = mysql_col(
            "updated",
            "timestamp",
            false,
            Some("CURRENT_TIMESTAMP(3)"),
            MySqlColumnMeta {
                column_type: "timestamp(3)".into(),
                extra: "DEFAULT_GENERATED on update CURRENT_TIMESTAMP(3)".into(),
                ..Default::default()
            },
        );
        assert_eq!(
            mysql_column_def(&updated, None),
            "`updated` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)"
        );
    }

    #[test]
    fn mysql_column_def_keeps_full_column_type_when_type_is_unchanged() {
        let col = StructureColumn {
            type_params: Some("10".into()),
            ..mysql_col(
                "n",
                "int unsigned",
                true,
                None,
                MySqlColumnMeta { column_type: "int(10) unsigned zerofill".into(), ..Default::default() },
            )
        };
        assert_eq!(mysql_column_def(&col, None), "`n` int(10) unsigned zerofill NULL");
        // A changed type is rendered with params before the modifier
        let e = edit("n", "n", "bigint unsigned", Some("20"), true, None);
        assert_eq!(mysql_column_def(&col, Some(&e)), "`n` bigint(20) unsigned NULL");
    }

    #[test]
    fn mysql_column_def_generated_column_has_no_default() {
        let col = mysql_col(
            "g",
            "varchar",
            true,
            None,
            MySqlColumnMeta {
                column_type: "varchar(40)".into(),
                extra: "STORED GENERATED".into(),
                generation_expr: Some("concat(`a`,_utf8mb4\\' x\\')".into()),
                ..Default::default()
            },
        );
        assert_eq!(
            mysql_column_def(&col, None),
            "`g` varchar(40) GENERATED ALWAYS AS (concat(`a`,_utf8mb4' x')) STORED NULL"
        );
    }

    // -- mysql_default_sql --

    #[test]
    fn mysql_default_sql_quotes_literals_and_wraps_expressions() {
        let d = |raw: Option<&str>, extra: &str, dt: &str| mysql_default_sql(raw.map(Into::into), extra, dt, false);
        assert_eq!(d(None, "", "varchar"), None);
        assert_eq!(d(Some("active"), "", "varchar"), Some("'active'".into()));
        assert_eq!(d(Some("it's"), "", "varchar"), Some("'it''s'".into()));
        assert_eq!(d(Some(""), "", "varchar"), Some("''".into()));
        assert_eq!(d(Some("0"), "", "int unsigned"), Some("0".into()));
        assert_eq!(d(Some("b'1'"), "", "bit"), Some("b'1'".into()));
        assert_eq!(d(Some("uuid()"), "DEFAULT_GENERATED", "varchar"), Some("(uuid())".into()));
        assert_eq!(
            d(Some("concat(_latin1\\'a\\')"), "DEFAULT_GENERATED", "varchar"),
            Some("(concat(_latin1'a'))".into())
        );
        assert_eq!(
            d(Some("CURRENT_TIMESTAMP"), "DEFAULT_GENERATED on update CURRENT_TIMESTAMP", "timestamp"),
            Some("CURRENT_TIMESTAMP".into())
        );
        // MySQL 5.7 reports CURRENT_TIMESTAMP without DEFAULT_GENERATED
        assert_eq!(d(Some("CURRENT_TIMESTAMP"), "", "datetime"), Some("CURRENT_TIMESTAMP".into()));
    }

    #[test]
    fn mysql_default_sql_passes_mariadb_defaults_through() {
        assert_eq!(mysql_default_sql(Some("'active'".into()), "", "varchar", true), Some("'active'".into()));
        assert_eq!(mysql_default_sql(Some("NULL".into()), "", "varchar", true), None);
    }

    // ── SQLite ALTER ─────────────────────────────────────────────────────

    #[test]
    fn sqlite_empty_changes_produces_nothing() {
        let stmts = generate_sqlite_alter("t", &[test_col("a", "text", true, None)], &empty_changes()).unwrap();
        assert!(stmts.is_empty());
    }

    #[test]
    fn sqlite_rename() {
        let current = vec![test_col("old", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("old", "new", "text", None, true, None)],
            ..empty_changes()
        };
        let stmts = generate_sqlite_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" RENAME COLUMN \"old\" TO \"new\";"]);
    }

    #[test]
    fn sqlite_drop() {
        let changes = StructureChanges { drops: vec!["col".into()], ..empty_changes() };
        let stmts = generate_sqlite_alter("t", &[], &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" DROP COLUMN \"col\";"]);
    }

    #[test]
    fn sqlite_add_nullable() {
        let changes = StructureChanges {
            adds: vec![add("col", "text", None, true, None)],
            ..empty_changes()
        };
        let stmts = generate_sqlite_alter("t", &[], &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ADD COLUMN \"col\" text;"]);
    }

    #[test]
    fn sqlite_add_not_null_with_default() {
        let changes = StructureChanges {
            adds: vec![add("col", "integer", None, false, Some("0"))],
            ..empty_changes()
        };
        let stmts = generate_sqlite_alter("t", &[], &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ADD COLUMN \"col\" integer NOT NULL DEFAULT 0;"]);
    }

    #[test]
    fn sqlite_add_with_type_params() {
        let changes = StructureChanges {
            adds: vec![add("name", "varchar", Some("100"), true, None)],
            ..empty_changes()
        };
        let stmts = generate_sqlite_alter("t", &[], &changes).unwrap();
        assert_eq!(stmts, vec!["ALTER TABLE \"t\" ADD COLUMN \"name\" varchar(100);"]);
    }

    #[test]
    fn sqlite_multiple_operations() {
        let current = vec![test_col("old", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("old", "renamed", "text", None, true, None)],
            drops: vec!["other".into()],
            adds: vec![add("new", "integer", None, true, Some("42"))],
            reorder: None,
        };
        let stmts = generate_sqlite_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts.len(), 3);
        assert!(stmts[0].contains("DROP"));
        assert!(stmts[1].contains("RENAME"));
        assert!(stmts[2].contains("ADD") && stmts[2].contains("DEFAULT 42"));
    }

    #[test]
    fn sqlite_rejects_type_change() {
        let current = vec![test_col("col", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("col", "col", "integer", None, true, None)],
            ..empty_changes()
        };
        let err = generate_sqlite_alter("t", &current, &changes).unwrap_err();
        assert!(err.contains("column types"));
    }

    #[test]
    fn sqlite_rejects_nullable_change() {
        let current = vec![test_col("col", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("col", "col", "text", None, false, None)],
            ..empty_changes()
        };
        let err = generate_sqlite_alter("t", &current, &changes).unwrap_err();
        assert!(err.contains("nullability"));
    }

    #[test]
    fn sqlite_rejects_default_change() {
        let current = vec![test_col("col", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("col", "col", "text", None, true, Some("'new'"))],
            ..empty_changes()
        };
        let err = generate_sqlite_alter("t", &current, &changes).unwrap_err();
        assert!(err.contains("column defaults"));
    }

    #[test]
    fn sqlite_rejects_reorder() {
        let changes = StructureChanges { reorder: Some(vec!["a".into()]), ..empty_changes() };
        assert!(generate_sqlite_alter("t", &[], &changes).is_err());
    }

    #[test]
    fn sqlite_rename_is_allowed_even_when_type_matches() {
        // Rename-only should succeed even though type/nullable/default are all checked
        let current = vec![test_col("a", "text", true, Some("'hi'"))];
        let changes = StructureChanges {
            edits: vec![edit("a", "b", "text", None, true, Some("'hi'"))],
            ..empty_changes()
        };
        let stmts = generate_sqlite_alter("t", &current, &changes).unwrap();
        assert_eq!(stmts.len(), 1);
        assert!(stmts[0].contains("RENAME"));
    }

    #[test]
    fn sqlite_nonexistent_edit_errors() {
        let current = vec![test_col("a", "text", true, None)];
        let changes = StructureChanges {
            edits: vec![edit("ghost", "ghost", "text", None, true, None)],
            ..empty_changes()
        };
        assert!(generate_sqlite_alter("t", &current, &changes).unwrap_err().contains("no longer exists"));
    }

    // -- Docker-backed integration tests --

    async fn start_mysql() -> (
        testcontainers_modules::testcontainers::ContainerAsync<Mysql>,
        sqlx::MySqlPool,
    ) {
        let container = Mysql::default().start().await.unwrap();
        let port = container.get_host_port_ipv4(3306).await.unwrap();
        let host = container.get_host().await.unwrap().to_string();
        let opts = MySqlConnectOptions::new().host(&host).port(port).username("root").database("test");
        let pool = MySqlPoolOptions::new().max_connections(1).connect_with(opts).await.unwrap();
        (container, pool)
    }

    async fn apply_mysql(pool: &sqlx::MySqlPool, table: &str, changes: &StructureChanges) -> Result<(), String> {
        let current = fetch_mysql_structure(pool, table).await?;
        let stmts = generate_mysql_alter(table, &current.columns, changes)?;
        DbPool::MySql(pool.clone())
            .execute_in_transaction(&stmts)
            .await
            .map_err(|e| e.to_string())
    }

    async fn mysql_extra(pool: &sqlx::MySqlPool, table: &str, column: &str) -> (String, String) {
        sqlx::query_as::<_, (String, String)>(
            "SELECT CAST(EXTRA AS CHAR), CAST(COLUMN_COMMENT AS CHAR) FROM information_schema.COLUMNS \
             WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ?",
        )
        .bind(table)
        .bind(column)
        .fetch_one(pool)
        .await
        .unwrap()
    }

    async fn mysql_column_order(pool: &sqlx::MySqlPool, table: &str) -> Vec<String> {
        sqlx::query_scalar::<_, String>(
            "SELECT CAST(COLUMN_NAME AS CHAR) FROM information_schema.COLUMNS \
             WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? ORDER BY ORDINAL_POSITION",
        )
        .bind(table)
        .fetch_all(pool)
        .await
        .unwrap()
    }

    #[tokio::test]
    #[ignore = "requires Docker"]
    async fn mysql_structure_edits_preserve_column_attributes() {
        let (_container, pool) = start_mysql().await;
        sqlx::query(
            "CREATE TABLE items ( \
                id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, \
                status VARCHAR(20) NOT NULL DEFAULT 'active' COMMENT 'lifecycle', \
                uid VARCHAR(36) DEFAULT (uuid()), \
                updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \
                label VARCHAR(20) DEFAULT (concat('a', 'b')), \
                g VARCHAR(40) AS (concat(status, ' x')) VIRTUAL \
             )",
        )
        .execute(&pool)
        .await
        .unwrap();

        let structure = fetch_mysql_structure(&pool, "items").await.unwrap();
        let status = structure.columns.iter().find(|c| c.name == "status").unwrap();
        assert_eq!(status.default_value.as_deref(), Some("'active'"));

        // Moving every column and toggling nullability rewrites each definition.
        let changes = StructureChanges {
            edits: vec![edit("status", "status", "varchar", Some("20"), true, Some("'active'"))],
            reorder: Some(vec![
                "g".into(), "label".into(), "updated".into(), "uid".into(), "status".into(), "id".into(),
            ]),
            ..empty_changes()
        };
        apply_mysql(&pool, "items", &changes).await.unwrap();

        assert_eq!(mysql_column_order(&pool, "items").await, ["g", "label", "updated", "uid", "status", "id"]);
        assert_eq!(mysql_extra(&pool, "items", "id").await.0, "auto_increment");
        assert_eq!(mysql_extra(&pool, "items", "status").await.1, "lifecycle");
        assert!(mysql_extra(&pool, "items", "updated").await.0.contains("on update CURRENT_TIMESTAMP"));
        assert!(mysql_extra(&pool, "items", "g").await.0.contains("VIRTUAL GENERATED"));

        let after = fetch_mysql_structure(&pool, "items").await.unwrap();
        let col = |name: &str| after.columns.iter().find(|c| c.name == name).unwrap().clone();
        assert!(col("status").is_nullable);
        assert_eq!(col("status").default_value.as_deref(), Some("'active'"));
        assert_eq!(col("uid").default_value.as_deref(), Some("(uuid())"));
        assert_eq!(col("label").default_value.as_deref(), Some("(concat(_utf8mb4'a',_utf8mb4'b'))"));

        // The id is still generated after the rewrite.
        sqlx::query("INSERT INTO items (status) VALUES ('x'), ('y')").execute(&pool).await.unwrap();
        let ids: Vec<u32> = sqlx::query_scalar("SELECT id FROM items ORDER BY id").fetch_all(&pool).await.unwrap();
        assert_eq!(ids, [1, 2]);
    }

    #[tokio::test]
    #[ignore = "requires Docker"]
    async fn mysql_structure_drop_rename_and_reorder_in_one_save() {
        let (_container, pool) = start_mysql().await;
        sqlx::query("CREATE TABLE people (a INT, b INT, c INT, full_name VARCHAR(10), name VARCHAR(10))")
            .execute(&pool)
            .await
            .unwrap();

        let changes = StructureChanges {
            edits: vec![
                edit("a", "a2", "int", None, true, None),
                edit("full_name", "name", "varchar", Some("10"), true, None),
            ],
            drops: vec!["name".into()],
            reorder: Some(vec!["a".into(), "c".into(), "b".into(), "full_name".into(), "name".into()]),
            adds: vec![add("e", "int", None, true, None)],
        };
        apply_mysql(&pool, "people", &changes).await.unwrap();

        assert_eq!(mysql_column_order(&pool, "people").await, ["a2", "c", "b", "name", "e"]);
    }

    #[tokio::test]
    #[ignore = "requires Docker"]
    async fn pg_structure_changes_roll_back_on_failure() {
        let container = Postgres::default().start().await.unwrap();
        let port = container.get_host_port_ipv4(5432).await.unwrap();
        let url = format!("postgres://postgres:postgres@127.0.0.1:{port}/postgres");
        let pool = PgPoolOptions::new().max_connections(1).connect(&url).await.unwrap();

        sqlx::query("CREATE TABLE stock (qty TEXT)").execute(&pool).await.unwrap();
        sqlx::query("INSERT INTO stock VALUES ('not a number')").execute(&pool).await.unwrap();

        // The rename succeeds, then the type change fails on the existing row.
        let changes = StructureChanges {
            edits: vec![edit("qty", "quantity", "integer", None, true, None)],
            ..empty_changes()
        };
        let current = fetch_pg_structure(&pool, "stock").await.unwrap();
        let stmts = generate_pg_alter("stock", &current.columns, &changes).unwrap();
        assert!(DbPool::Postgres(pool.clone()).execute_in_transaction(&stmts).await.is_err());

        let after = fetch_pg_structure(&pool, "stock").await.unwrap();
        assert_eq!(after.columns[0].name, "qty");
        assert_eq!(after.columns[0].data_type, "text");
    }
}
