use serde::Serialize;

use crate::commands::connection::{AppState, DbPool};

use super::sql_util::{mysql_quote, pg_quote};

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TableDdl {
    pub ddl: String,
    pub dialect: String,
    pub source: String,
}

struct PgColumnDdl {
    name: String,
    data_type: String,
    not_null: bool,
    default_expr: Option<String>,
    identity: String,
    serial_type: Option<String>,
}

struct PgConstraintDdl {
    name: String,
    definition: String,
}

fn ensure_semicolon(sql: String) -> String {
    let trimmed = sql.trim();
    if trimmed.ends_with(';') {
        trimmed.to_string()
    } else {
        format!("{trimmed};")
    }
}

fn render_pg_create_table(
    table: &str,
    columns: Vec<PgColumnDdl>,
    constraints: Vec<PgConstraintDdl>,
) -> String {
    let mut lines: Vec<String> = columns
        .into_iter()
        .map(|column| {
            let data_type = column.serial_type.as_deref().unwrap_or(&column.data_type);
            let mut line = format!("  {} {}", pg_quote(&column.name), data_type);

            match column.identity.as_str() {
                "a" => line.push_str(" GENERATED ALWAYS AS IDENTITY"),
                "d" => line.push_str(" GENERATED BY DEFAULT AS IDENTITY"),
                _ => {
                    if column.serial_type.is_none() {
                        if let Some(default_expr) = column.default_expr {
                            line.push_str(" DEFAULT ");
                            line.push_str(&default_expr);
                        }
                    }
                }
            }

            if column.not_null && column.serial_type.is_none() {
                line.push_str(" NOT NULL");
            }

            line
        })
        .collect();

    lines.extend(constraints.into_iter().map(|constraint| {
        format!(
            "  CONSTRAINT {} {}",
            pg_quote(&constraint.name),
            constraint.definition
        )
    }));

    format!(
        "CREATE TABLE {} (\n{}\n);",
        pg_quote(table),
        lines.join(",\n")
    )
}

async fn fetch_postgres_ddl(pool: sqlx::PgPool, table: &str) -> Result<TableDdl, String> {
    let relkind = sqlx::query_scalar::<_, String>(
        "SELECT c.relkind::text \
         FROM pg_catalog.pg_class c \
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace \
         WHERE c.relname = $1 AND n.nspname = 'public'",
    )
    .bind(table)
    .fetch_optional(&pool)
    .await
    .map_err(|e| e.to_string())?
    .ok_or_else(|| format!("Table not found: {table}"))?;

    if relkind != "r" && relkind != "p" {
        return Err("DDL is only available for tables".to_string());
    }

    let column_rows =
        sqlx::query_as::<_, (String, String, bool, Option<String>, String, Option<String>)>(
            "SELECT \
            a.attname, \
            pg_catalog.format_type(a.atttypid, a.atttypmod), \
            a.attnotnull, \
            pg_catalog.pg_get_expr(ad.adbin, ad.adrelid), \
            a.attidentity::text, \
            CASE \
                WHEN serial_seq.oid IS NULL THEN NULL \
                WHEN a.atttypid = 'pg_catalog.int2'::regtype THEN 'smallserial'::text \
                WHEN a.atttypid = 'pg_catalog.int4'::regtype THEN 'serial'::text \
                WHEN a.atttypid = 'pg_catalog.int8'::regtype THEN 'bigserial'::text \
                ELSE NULL \
            END \
         FROM pg_catalog.pg_attribute a \
         JOIN pg_catalog.pg_class c ON c.oid = a.attrelid \
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace \
         LEFT JOIN pg_catalog.pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum \
         LEFT JOIN LATERAL ( \
            SELECT seq.oid \
            FROM pg_catalog.pg_depend dep \
            JOIN pg_catalog.pg_class seq ON seq.oid = dep.objid AND seq.relkind = 'S' \
            WHERE dep.refobjid = a.attrelid \
                AND dep.refobjsubid = a.attnum \
                AND dep.deptype = 'a' \
                AND a.attidentity = '' \
                AND a.attnotnull \
                AND ad.adbin IS NOT NULL \
                AND pg_catalog.pg_get_expr(ad.adbin, ad.adrelid) LIKE 'nextval(%' \
            LIMIT 1 \
         ) serial_seq ON TRUE \
         WHERE c.relname = $1 \
            AND n.nspname = 'public' \
            AND a.attnum > 0 \
            AND NOT a.attisdropped \
         ORDER BY a.attnum",
        )
        .bind(table)
        .fetch_all(&pool)
        .await
        .map_err(|e| e.to_string())?;

    let columns = column_rows
        .into_iter()
        .map(
            |(name, data_type, not_null, default_expr, identity, serial_type)| PgColumnDdl {
                name,
                data_type,
                not_null,
                default_expr,
                identity,
                serial_type,
            },
        )
        .collect();

    let constraints = sqlx::query_as::<_, (String, String)>(
        "SELECT \
            con.conname, \
            pg_catalog.pg_get_constraintdef(con.oid, true) \
         FROM pg_catalog.pg_constraint con \
         JOIN pg_catalog.pg_class c ON c.oid = con.conrelid \
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace \
         WHERE c.relname = $1 \
            AND n.nspname = 'public' \
            AND con.contype IN ('p', 'u', 'c', 'f', 'x') \
         ORDER BY \
            CASE con.contype \
                WHEN 'p' THEN 1 \
                WHEN 'u' THEN 2 \
                WHEN 'f' THEN 3 \
                WHEN 'c' THEN 4 \
                WHEN 'x' THEN 5 \
                ELSE 6 \
            END, \
            con.conname",
    )
    .bind(table)
    .fetch_all(&pool)
    .await
    .map_err(|e| e.to_string())?
    .into_iter()
    .map(|(name, definition)| PgConstraintDdl { name, definition })
    .collect();

    Ok(TableDdl {
        ddl: render_pg_create_table(table, columns, constraints),
        dialect: "postgres".to_string(),
        source: "generated".to_string(),
    })
}

async fn fetch_mysql_ddl(pool: sqlx::MySqlPool, table: &str) -> Result<TableDdl, String> {
    let table_type = sqlx::query_scalar::<_, String>(
        "SELECT CAST(TABLE_TYPE AS CHAR) \
         FROM information_schema.TABLES \
         WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?",
    )
    .bind(table)
    .fetch_optional(&pool)
    .await
    .map_err(|e| e.to_string())?
    .ok_or_else(|| format!("Table not found: {table}"))?;

    if table_type != "BASE TABLE" {
        return Err("DDL is only available for tables".to_string());
    }

    let sql = format!("SHOW CREATE TABLE {}", mysql_quote(table));
    let (_, ddl) = sqlx::query_as::<_, (String, String)>(sqlx::AssertSqlSafe(sql))
        .fetch_one(&pool)
        .await
        .map_err(|e| e.to_string())?;

    Ok(TableDdl {
        ddl: ensure_semicolon(ddl),
        dialect: "mysql".to_string(),
        source: "native".to_string(),
    })
}

async fn fetch_sqlite_ddl(pool: sqlx::SqlitePool, table: &str) -> Result<TableDdl, String> {
    let row = sqlx::query_as::<_, (String, Option<String>)>(
        "SELECT type, sql FROM sqlite_master \
         WHERE name = ? AND type IN ('table', 'view')",
    )
    .bind(table)
    .fetch_optional(&pool)
    .await
    .map_err(|e| e.to_string())?
    .ok_or_else(|| format!("Table not found: {table}"))?;

    if row.0 != "table" {
        return Err("DDL is only available for tables".to_string());
    }

    let ddl = row
        .1
        .ok_or_else(|| format!("No CREATE TABLE SQL is available for {table}"))?;

    Ok(TableDdl {
        ddl: ensure_semicolon(ddl),
        dialect: "sqlite".to_string(),
        source: "native".to_string(),
    })
}

#[tauri::command]
pub async fn fetch_table_ddl(
    connection_id: String,
    table: String,
    state: tauri::State<'_, AppState>,
) -> Result<TableDdl, String> {
    let pool = {
        let pools = state.pools.lock().unwrap();
        pools
            .get(&connection_id)
            .ok_or_else(|| "Connection not found".to_string())?
            .clone()
    };

    match pool {
        DbPool::Postgres(pg) => fetch_postgres_ddl(pg, &table).await,
        DbPool::MySql(mysql) => fetch_mysql_ddl(mysql, &table).await,
        DbPool::Sqlite(sqlite) => fetch_sqlite_ddl(sqlite, &table).await,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sqlx::postgres::PgPoolOptions;
    use testcontainers_modules::{postgres::Postgres, testcontainers::runners::AsyncRunner};

    #[test]
    fn ensure_semicolon_appends_only_when_missing() {
        assert_eq!(
            ensure_semicolon("CREATE TABLE items (id integer)".to_string()),
            "CREATE TABLE items (id integer);"
        );
        assert_eq!(
            ensure_semicolon("CREATE TABLE items (id integer);".to_string()),
            "CREATE TABLE items (id integer);"
        );
    }

    #[test]
    fn render_pg_create_table_includes_columns_and_constraints() {
        let ddl = render_pg_create_table(
            "items",
            vec![
                PgColumnDdl {
                    name: "id".to_string(),
                    data_type: "integer".to_string(),
                    not_null: true,
                    default_expr: Some("nextval('items_id_seq'::regclass)".to_string()),
                    identity: String::new(),
                    serial_type: None,
                },
                PgColumnDdl {
                    name: "name".to_string(),
                    data_type: "text".to_string(),
                    not_null: true,
                    default_expr: Some("'untitled'::text".to_string()),
                    identity: String::new(),
                    serial_type: None,
                },
            ],
            vec![
                PgConstraintDdl {
                    name: "items_pkey".to_string(),
                    definition: "PRIMARY KEY (id)".to_string(),
                },
                PgConstraintDdl {
                    name: "items_name_key".to_string(),
                    definition: "UNIQUE (name)".to_string(),
                },
                PgConstraintDdl {
                    name: "items_name_check".to_string(),
                    definition: "CHECK (name <> ''::text)".to_string(),
                },
            ],
        );

        assert!(ddl.contains("CREATE TABLE \"items\""));
        assert!(ddl.contains("\"id\" integer DEFAULT nextval('items_id_seq'::regclass) NOT NULL"));
        assert!(ddl.contains("\"name\" text DEFAULT 'untitled'::text NOT NULL"));
        assert!(ddl.contains("CONSTRAINT \"items_pkey\" PRIMARY KEY (id)"));
        assert!(ddl.contains("CONSTRAINT \"items_name_key\" UNIQUE (name)"));
        assert!(ddl.contains("CONSTRAINT \"items_name_check\" CHECK (name <> ''::text)"));
    }

    #[test]
    fn render_pg_create_table_prefers_identity_over_default() {
        let ddl = render_pg_create_table(
            "items",
            vec![PgColumnDdl {
                name: "id".to_string(),
                data_type: "bigint".to_string(),
                not_null: true,
                default_expr: Some("nextval('items_id_seq'::regclass)".to_string()),
                identity: "d".to_string(),
                serial_type: None,
            }],
            vec![],
        );

        assert!(ddl.contains("\"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assert!(!ddl.contains("nextval"));
    }

    #[test]
    fn render_pg_create_table_uses_serial_for_owned_sequence_defaults() {
        let ddl = render_pg_create_table(
            "items",
            vec![PgColumnDdl {
                name: "id".to_string(),
                data_type: "integer".to_string(),
                not_null: true,
                default_expr: Some("nextval('items_id_seq'::regclass)".to_string()),
                identity: String::new(),
                serial_type: Some("serial".to_string()),
            }],
            vec![PgConstraintDdl {
                name: "items_pkey".to_string(),
                definition: "PRIMARY KEY (id)".to_string(),
            }],
        );

        assert!(ddl.contains("\"id\" serial"));
        assert!(!ddl.contains("nextval"));
        assert!(ddl.contains("CONSTRAINT \"items_pkey\" PRIMARY KEY (id)"));
    }

    #[tokio::test]
    #[ignore = "requires Docker"]
    async fn fetch_postgres_ddl_preserves_serial_and_table_constraints() {
        let container = Postgres::default().start().await.unwrap();
        let port = container.get_host_port_ipv4(5432).await.unwrap();
        let url = format!("postgres://postgres:postgres@127.0.0.1:{port}/postgres");
        let pool = PgPoolOptions::new()
            .max_connections(1)
            .connect(&url)
            .await
            .unwrap();

        sqlx::query("CREATE TABLE parents (id SERIAL PRIMARY KEY)")
            .execute(&pool)
            .await
            .unwrap();
        sqlx::query(
            "CREATE TABLE items ( \
                id SERIAL PRIMARY KEY, \
                name TEXT NOT NULL UNIQUE, \
                quantity INTEGER NOT NULL CHECK (quantity > 0), \
                parent_id INTEGER REFERENCES parents(id) \
             )",
        )
        .execute(&pool)
        .await
        .unwrap();

        let ddl = fetch_postgres_ddl(pool, "items").await.unwrap().ddl;

        assert!(ddl.contains("\"id\" serial"));
        assert!(!ddl.contains("nextval"));
        assert!(ddl.contains("PRIMARY KEY (id)"));
        assert!(ddl.contains("UNIQUE (name)"));
        assert!(ddl.contains("CHECK"));
        assert!(ddl.contains("quantity > 0"));
        assert!(ddl.contains("FOREIGN KEY (parent_id) REFERENCES parents(id)"));
    }
}
